apiVersion: v1
kind: Namespace
metadata:
  name:  devops
  labels:
    istio-injection: enabled

---

apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-gcp
spec:
  # replace this with your own gcp project id
  projectID: timpamungkas-udemy
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: gcp-credential
      key: credential